Repository UBC-MDS/DSCI-532_2025_22_nyc-arrest-tracker, pull requests merged in 2025-03, with the labels that each got.

#59 Update dashboard to add toggle for map for boroughs vs precincts
  src/app.py
Labels: enhancement

#61 Feature: Add interactivity between map and pie chart for crime frequency.
  src/app.py
Labels: enhancement

#63 feat: Add sidebar and move the toggle switch to the sidebar
  src/app.py
Labels: enhancement

#70 feat: add calendar to side bar
  src/app.py
Labels: documentation

#76 docs: Complete reflection
  reports/m2_reflection.md
Labels: documentation

#74 feat: Add short description to bottom of dashboard
  src/app.py
Labels: enhancement

#87 Fix: Refactor code to remove unnecessary geojson transformations
  src/app.py
Labels: bug

#90 Refactor: Split app.py into multiple files
  src/app.py
  src/callbacks/__init__.py
  src/callbacks/buttons.py
  src/callbacks/charts.py
  src/callbacks/map.py
  src/components/__init__.py
  src/components/charts.py
  src/components/general.py
  src/components/map.py
  src/data/__init__.py
  src/data/data.py
  src/utils/__init__.py
  src/utils/helpers.py
Labels: refactor

#95 Feat: Add calendar interactivity
  src/callbacks/charts.py
  src/callbacks/map.py
  src/data/data.py
  src/utils/__init__.py
  src/utils/helpers.py
Labels: enhancement

#97 Update environment.yml to update plotly to 6.0.0 from 5.8.0
  environment.yml
Labels: build

#98 feat: Update title layout
  src/app.py
  src/components/general.py
Labels: enhancement

#99 fix: update pie chart
  src/utils/helpers.py
Labels: enhancement

#104 fix: change freq pie chart to bar chart
  src/app.py
  src/callbacks/charts.py
  src/components/__init__.py
  src/components/charts.py
  src/utils/__init__.py
  src/utils/helpers.py
Labels: enhancement

#110 Feat: chart visual improvements
  src/components/charts.py
  src/utils/helpers.py
Labels: bug, enhancement

#112 feat: update last updated date to March 9th
  src/components/general.py
Labels: documentation

#108 docs: Started on reflection 3
  reports/m3_reflection.md
Labels: documentation

#114 Update m3_reflection.md
  reports/m3_reflection.md
Labels: documentation

#115 Update README.md
  README.md
Labels: documentation

#116 docs: Uploaded new gif for Milestone 3
  img/demo.gif
Labels: documentation

#142 Feat add loading indicators
  src/components/charts.py
  src/components/map.py
Labels: enhancement

#146 feat: Add dynamic map title
  src/callbacks/map.py
Labels: enhancement

#147 feat: grey out regions
  src/callbacks/charts.py
  src/callbacks/map.py
Labels: bug, enhancement

#149 feat: Improve dashboard layout
  src/app.py
  src/callbacks/map.py
  src/components/__init__.py
  src/components/general.py
  src/components/map.py
Labels: enhancement

#151 feat: remove chart zoom and actions
  src/assets/style.css
  src/utils/helpers.py
Labels: enhancement

#152 feat: Change cursor
  src/assets/style.css
  src/callbacks/map.py
Labels: enhancement

#154 feat: Update date
  src/components/general.py
Labels: enhancement

#155 feat: add sidebar transitions
  src/assets/style.css
  src/callbacks/buttons.py
  src/components/general.py
Labels: enhancement

#158 fix: pie title cutoff
  src/app.py
  src/callbacks/charts.py
  src/utils/helpers.py
Labels: bug

#163 Milestone 4 reflection
  reports/m4_reflection.md
Labels: documentation

#162 doc: update Readme
  README.md
Labels: documentation
